name: Deploy on Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Push Docker image to Heroku
        run: |
          heroku_app_name=java-cicd
          docker build -t registry.heroku.com/$heroku_app_name/web .
          docker push registry.heroku.com/$heroku_app_name/web

      - name: Release Docker image on Heroku
        run: |
          heroku_app_name=java-cicd
          curl -n -X PATCH https://api.heroku.com/apps/$heroku_app_name/formation \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
            -d '{"updates":[{"type":"web","docker_image":"registry.heroku.com/'"$heroku_app_name"'/web"}]}'